fix: 캠 끄면 불빛 없어짐
ssafy-null/fe pull request #137
Opened 2021-08-06 16:24 UTC by minho-jang

2021-08-06 23:45 UTC, dididy requested changes
이걸 해내다니 수고 많으셨습니다! 

아까 같이 테스트했을 때 말씀드린 것 처럼 아래 모달 언마운트시점에 버튼클릭시 실행했던 함수를 연결하면 문제를 방금 발생한 이슈를 해결할 수 있을 것 같습니다

FE/components/webrtc/VideoRoomConfigModal.tsx

2021-08-07 00:23 UTC, minho-jang commented
> 이걸 해내다니 수고 많으셨습니다!
> 
> 아까 같이 테스트했을 때 말씀드린 것 처럼 아래 모달 언마운트시점에 버튼클릭시 실행했던 함수를 연결하면 문제를 방금 발생한 이슈를 해결할 수 있을 것 같습니다
> 
> FE/components/webrtc/VideoRoomConfigModal.tsx

네, 컴포넌트가 언마운트 되는 시점이 아니라, state가 해제(?)되는 시점에 함수를 실행하니 해결되었습니다

2021-08-07 02:51 UTC, dididy approved these changes
네네 deps가 빈배열이면 값을 갱신하지 않으니까 생기는 문제인 것 같습니다

찾아보니 hook도 클로져였네요

https://hewonjeong.github.io/deep-dive-how-do-react-hooks-really-work-ko/

수고하셨습니다!

2021-08-07 05:05 UTC, Dongkyun-Jang approved these changes

2021-08-07 05:06 UTC, merged