3가지의 기능을 가진 ProtectedRoute를 정의합니다
ssafy-null/fe pull request #220
Opened 2021-08-12 17:49 UTC by Dongkyun-Jang

> Resolve [#S05P13A202-311](https://jira.ssafy.com/browse/S05P13A202-311)

1. 토큰은 있지만 상태값이 없는 경우 상태값을 가져옵니다
2. 페이지 전환시 로딩 스피너를 작동시킵니다
3. 로그인하지 않은 유저가 다른 곳으로 가지 못하게 합니다(민호님 코드 이사)

### 이 과정에서 알게된 점
민호님이 과거에 alert 창이 3번뜬다고 말씀해주셨습니다. 하나는 제가 찾아서 고쳤는데 나머지 하나는 도저히 찾을 수가 없었습니다. 때문에 조금 찾아보니 alert 창을 띄우고 화면을 전환시키면 unMount 작업과 mount 작업이 맞물리면서 alert 창이 두번 나오는 버그가 발생한다고 합니다.

2021-08-12 20:48 UTC, dididy requested changes
수고많으셨어요~~~!

2021-08-12 20:48 UTC, dididy commented on FE/components/organisms/ProtectedRoute/ProtectedRoute.tsx
> +  children: JSX.Element;
https://simsimjae.tistory.com/426

JSX.Element, ReactNode, ReactElement 세가지 타입에 대해서 제대로 이해하지 못하고 있었는데 이번기획에 알게되었네요 감사합니다!

아래를 보니 null이 return 될 수 있는 상황인 것 같은데 유니온으로 null도 처리되면 더욱 좋을 것 같습니다!

2021-08-12 20:48 UTC, dididy commented on FE/components/organisms/ProtectedRoute/ProtectedRoute.tsx
> +    };
코드가 엄청 깔끔해 지는군요

2021-08-12 20:48 UTC, dididy commented on FE/components/organisms/ProtectedRoute/ProtectedRoute.tsx
> +    ];
rtc쪽도 추가해주시면 좋을 것 같습니다~

2021-08-13 00:11 UTC, minho-jang commented on FE/components/organisms/ProtectedRoute/ProtectedRoute.tsx
> +    ];
/admin 도 추가해주세요!

2021-08-13 00:23 UTC, Dongkyun-Jang commented on FE/components/organisms/ProtectedRoute/ProtectedRoute.tsx
> +    ];
넵 !! 추가하도록 하겠습니다.

2021-08-13 01:52 UTC, dididy approved these changes

2021-08-13 05:45 UTC, merged